name: CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, world!" > output.out

      # next step, upload output.out as an artifact, note this is in the DIR $GITHUB_WORKSPACE
      - name: Upload output.out as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: output.out
          path: output.out